<?php

	class ContentProGoogleNews {
		
		var $name = "Google News";
		var $typ = "Plugin";
		var $classname = "ContentProGoogleNews";
		var $table = "ContentProGoogleNews";
		var $description = "A Google News Sitemap is a file that allows you to control which content you submit to Google News. ";
		
		function __construct(){
			
			
			
			
			
			
			$this->__createnewsfile($this->__createnewscontent());

		}
		
		
		function __createnewscontent(){
			
			//publication SETTINGS
			$publication = "\t\t\t<news:publication>";
			$publication.= "\t\t\t\t<news:name>".get_bloginfo('name')."</news:name>";
			$publication.= "\t\t\t\t<news:language>".get_bloginfo('language')."</news:language>";
			$publication.= "\t\t\t</news:publication>";
			
			$data = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
			$data.= "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:news=\"http://www.google.com/schemas/sitemap-news/0.9\">\n";

			$data.= "<!-- Generated by ContentPro for Wordpress | Google News -->\n";
			$data.= "<!-- Created by Benjamin Kott | http://www.bk2k.info -->\n";
			
			$data.= "\t<url>\n";
			$data.= "\t\t<loc>http://www.example.org/business/article55.html</loc>\n";
			$data.= "\t\t<news:news>\n";
			$data.= $publication;
			$data.= "\t\t\t<news:access>Subscription</news:access>\n";
      $data.= "\t\t\t<news:genres>PressRelease, Blog</news:genres>\n";
      $data.= "\t\t\t<news:publication_date>2008-12-23</news:publication_date>\n";
      $data.= "\t\t\t<news:title>Companies A, B in Merger Talks</news:title>\n";
      $data.= "\t\t\t<news:keywords>business, merger, acquisition, A, B</news:keywords>\n";
      $data.= "\t\t\t<news:stock_tickers>NASDAQ:A, NASDAQ:B</news:stock_tickers>\n";
			$data.= "\t\t</news:news>\n";
			$data.= "\t</url>\n";
			
			$data.= "</urlset>\n";
			$data.= "<!-- Last build time: ".date("F j, Y, g:i a")."-->";
			
			return $data;
			
		}
		
		
		
		function __createnewsfile($data = ""){
			
			
			$file = "../contentpro-google-news-sitemap.xml";
			$fp = fopen($file, "w+"); // open the cache file "google-news-sitemap.xml" for writing
			fwrite($fp, $data); // save the contents of output buffer to the file
			fclose($fp); // close the file
			
			echo "done";
			
			
		}
		
	}
	
?>